<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DroidIDE.Core\DroidIDE.Core.csproj" />
    <ProjectReference Include="..\DroidIDE.Terminal\DroidIDE.Terminal.csproj" />
  </ItemGroup>

</Project>
