<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Build\" />
    <Folder Include="DotnetManager\" />
    <Folder Include="Run\" />
    <Folder Include="ServiceManager\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DroidIDE.Core\DroidIDE.Core.csproj" />
  </ItemGroup>

</Project>
